### ISSUE TITLE
v-scroll method not called on body.

### ISSUE THREAD

**Issue by MichMich** [wangpin34/vue-scroll#1]
First of all, thanks for the nice library!

I tried to get it working within a webpage, but was unable to get it working on the body element.

```
<body id="app" v-scroll="onScroll">
...
</body>
```

This does not seem to work. However, when I add it to a scrollable div within the body, it works:

```
<body id="app">
    <div style="height: 200px; overflow: scroll"  v-scroll="onScroll">
        ...
    </div>
</body>
```

I tried it in Chrome and Safari. Both browsers have the same issue. Any idea?

**Comment by wangpin34** [comment]
@MichMich  Thanks for your reporter. Appreciate

<hr/>

I did some researches about scroll event. 
1.  Register onscroll on body, there are two ways. One works but another doesn't. Unfortunately vue-scroll uses the one that doesn't work. 

```
//Does't work
bodyObj.addEventListener('scroll', function(){...})

//Works
bodyObj.onscroll = function(){...}
```
1. Previously when we tried to register scroll event on whole window( on body ), there are serveral approaches could work

```
window.addEventListener('scroll',function(){}) or window.onscroll

document.body.onscroll = function(){}

document.addEventListener('scroll',function(){}) or document.onscroll = function(){}

```

The intersting part is , event target is **document** in each approach.
It seems like that the document is the only scrollable object when scrolling the whole window.

**But**, the scroll position is recorded in body object. So if we want to moniter scroll event and log position, we need code like following.

```
window.onscroll = function(){
    console.log('scroll top is : ' + document.body.scrollTop)
}
```

<hr/>

Any idea for fix this nicely?

**Comment by Guilty1866** [comment]
_main.js_
`import VueScroll from 'vue-scroll'`
`Vue.use(VueScroll)`

_app.vue_
`<template>
<div v-scroll="onScroll" >
  <div class="head" v-show="!$route.params.id ">
      <h1 class="title float-left">约洛影视</h1>  
      <div class="head-right float-right">
        <icon type="info_circle"></icon>
         <icon type="search"></icon>
      </div>     
  </div>
  <sticky>
    <div class="nav" v-show="!$route.params.id ">
      <tab :line-width="2" active-color="#fff" default-color="#888">       
        <tab-item :selected="demo1 === '美剧'" @click="demo1 = '美剧'" v-link="'/home'">美剧</tab-item>
        <tab-item :selected="demo1 === '资讯'" @click="demo1 = '资讯'" v-link="'/news'">资讯</tab-item>
        <tab-item :selected="demo1 === '相册'" @click="demo1 = '相册'" v-link="'/albums'">相册</tab-item>
      </tab>
    </div>
  </sticky> 
   <router-view></router-view>
   <div class="footer">
     <p>© 约洛影视网络技术股份有限公司版权所有 鄂B2-20160815-25</p>
   </div>
  <div class="top" v-show="showTop" @touchstart.stop="returnTop" >
    <P>{{position.scrollTop}}</P>
  </div>
</div>   
</template>

<script>
import Group from 'vux/dist/components/group'
import Cell from 'vux/dist/components/cell'
import Tab from 'vux/dist/components/tab'
import TabItem from 'vux/dist/components/tab-item'
import Icon from 'vux/dist/components/icon'
import Sticky from 'vux/dist/components/sticky'

export default {
  data () {
    return {
      demo1: '资讯',
      showTop: true,
      position: {scrollTop: 0, scrollLeft: 0}
    }
  },
  components: {
    Group,
    Cell,
    Tab,
    TabItem,
    Icon,
    Sticky
  },
  methods: {
    returnTop: function () {
      window.scrollTo(0, 0)
      this.showTop = false
    },
    onScroll: function (e, position) {
      this.position = position
    }
  }
}
</script>`
无法监听到滚动，怎么解决？

**Comment by Guilty1866** [comment]
_main.js_
`import VueScroll from 'vue-scroll'`
`Vue.use(VueScroll)`

_app.vue_
`methods: {onScroll: function (e, position){...}}`
无法监听到滚动，怎么解决？

**Comment by Guilty1866** [comment]
`<div v-scroll="onScroll" >...</div>`

**Comment by wangpin34** [comment]
@Guilty1866 对不起没有先看到这里，还以为你是用的body尝试的。
我明天会测试下，看看是不是发布的代码有问题。

谢谢

**Comment by wangpin34** [comment]
fixed in [the latest commit](https://github.com/wangpin34/vue-scroll/commit/069e26484bb0f80034f34aaa488f440ba7444ebe)

**Comment by shamrin** [comment]
According to a [StackOverflow answer][1], you can also do:

> You should be able to attach a document-level listener with a third parameter of `true` to capture the scroll events on all elements. Here's what that looks like:

```javascript
document.addEventListener('scroll', function(e){ }, true);
```

> The `true` at the end is the important part, it tells the browser to capture the event on dispatch, even if that event does not normally bubble, like change, focus, and scroll.

Important advantage - you can later remove the listener if needed:

```javascript
document.addEventListener('scroll', onScroll, true);
// …
document.removeEventListener('scroll', onScroll, true);
```
[1]: https://stackoverflow.com/a/30723677

**Comment by wangpin34** [comment]
@shamrin  It's a great advantage that only one scroll listener been created and attached.  And I will implement it later on.  Thank you.
