### ISSUE TITLE
怎么可以监听body的滚动呢？

### ISSUE THREAD

**Issue by imguoc** [wangpin34/vue-scroll#11]
如题，我试了下能监听到内滚动，不知道怎么监听到body。
vue2.0不能以body为el挂载。
Do not mount Vue to <html> or <body> - mount to normal elements instead.

**Comment by wangpin34** [comment]
@sxgc 是的，所以，vue-scroll 2.x 也不能监听 body 的滚动。稍后我会更新下 readme。对你造成困扰的话，很抱.歉，:)
