### ISSUE TITLE
vue2中不知道怎么引入使用，应该在main.js中引入还是在组件中引入，如何引入？

### ISSUE THREAD

**Issue by taoyingsong** [wangpin34/vue-scroll#12]

**Comment by wangpin34** [comment]
@taoyingsong 请看一下这个 [demo](https://github.com/wangpin34/vue-scroll/tree/2.0-compatible/samples/vue-cli-webpack)。 
简单来说就是先[加载](http://cn.vuejs.org/v2/guide/plugins.html#使用插件) 

```
Vue.use(vuescroll)
```
然后可以作为普通的 [event](http://cn.vuejs.org/v2/guide/events.html#监听事件) 一样使用

**Comment by wangpin34** [comment]
@taoyingsong 如果还有问题，请重新打开这个 issue，我会回复你。
