### ISSUE TITLE
Vue is not loaded yet. Please make sure it is loaded before installing vue-scroll

### ISSUE THREAD

**Issue by behnamjz** [wangpin34/vue-scroll#13]
hi
i'm laoded vue and vue-scroll like [this](https://jsfiddle.net/behnamjz/879sjfLg/3/) But scroll is not working  and show this error on my console "Vue is not loaded yet. Please make sure it is loaded before installing vue-scroll".

why??

**Comment by wangpin34** [comment]
fixed by https://github.com/wangpin34/vue-scroll/pull/14
