### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by wangpin34** [wangpin34/vue-scroll#16]
Use event delegation to improve performance

**Comment by wangpin34** [comment]
Anyone who wants to implement this feature, come on :)

**Comment by IEfucker** [comment]
&debounce

**Comment by oshnix** [comment]
@wangpin34  Do you have any ideas on implementing event delegation for scroll? Cause it doesn't bubble up.    
@IEfucker I can try to implement it. Argument can be passed to vue directive like this:     
'v-scroll:400="onScroll"' where 400 will be ms count for debounce function

**Comment by wangpin34** [comment]
A debounce also be required. I will cover this in the next change by myself. Thank you all. :)
