### ISSUE TITLE
v2.1.0 is comming

### ISSUE THREAD

**Issue by wangpin34** [wangpin34/vue-scroll#18]
v2.1.0 is comming with more powerful onto scroll thing.

* Throttle
* Debounce
* ...

It's still in development. Welcome come for ideas, PRs, any kind of contributions!

**Comment by EHackettTriCore** [comment]
👍🏼 I'm wrapping the scroll event in a _.debounce function through lodash at the moment but it's preventing ios from momentum scrolling so hopefully your native solution will solve my hack. Thanks for this plugin!

**Comment by wangpin34** [comment]
@EHackettTriCore Welcome. May be you can share your code below so that I can help you on that.

**Comment by Ethanhackett** [comment]
@wangpin34 oh sorry I just saw your comment. Used the wrong git account. I don't think it's actually an issue with your plugin but a bug with ios scrolling and calculating fixed position. For those looking for a debounce in the mean time this his how I did it with Lodash.

```javascript
onScroll: _.debounce(function(e, position){
        //Do the stuff
      }, 50),
```

I have a fixed element in side of a scrolling element and the fixed position freezes while momentum scrolling. I'll have to move the fixed elements outside of the scrolling elements.

**Comment by wangpin34** [comment]
@EHackettTriCore  It seems like an issue that how you struct those components.  A fixed component within a scrolling component(Correct me if anything wrong).  But this plugin works on monitor scroll event on specify component and executing functions which have been bind to the event. 

The issue you have described is a specify case so I think it's better to have a live demo on jsfiddle etc, and ask a question on stackoverflow.  I'm glad to help you on that after then.

**Comment by wangpin34** [comment]
I refactor some of the code and import throttle and debounce from lodash to reduce mess. Now v2.1.0 is published. Thanks for all your help. Cheers !!! @EHackettTriCore

**Comment by wangpin34** [comment]
Close this issue since v2.1.0 is published.
