### ISSUE TITLE
建议在README中介绍引入方式

### ISSUE THREAD

**Issue by liujunyang** [wangpin34/vue-scroll#19]
比如：
* let VueScroll = require('vue-scroll') // 不是ES6模块，而是CommonJs模块
* 通过script标签引入

**Comment by wangpin34** [comment]
是的，这是很好的建议。如果你感兴趣的话，也可以fork这个项目，修改 readme，然后提交 pr。我们一起合作，让它更加的好用。

ps. 事实上我也有考虑过类似的问题，并且做了几个 sample
项目，可以参考下 readme 中 sample 这个章节。

**Comment by wangpin34** [comment]
Done in https://github.com/wangpin34/vue-scroll/commit/a14af8559e9a049b1cfdf858bd18bdfb636f6707. And for more details, please refer to demos under https://github.com/wangpin34/vue-scroll/tree/2.0-compatible/samples
