### ISSUE TITLE
无法监听到滚动，怎么解决？

### ISSUE THREAD

**Issue by Guilty1866** [wangpin34/vue-scroll#2]
main.js
import VueScroll from 'vue-scroll'
Vue.use(VueScroll)

app.vue
methods: {onScroll: function (e, position){...}}
无法监听到滚动，怎么解决？

**Comment by wangpin34** [comment]
@Guilty1866  

console 中有错误信息吗？ 贴一下。谢谢

ps: 不需要显示的[安装插件](https://vuejs.org.cn/api/#Vue-use), vue-scroll 在载入后自动检测 Vue 并安装

**Comment by wangpin34** [comment]
Close this issue cause no further details provided.

**Comment by wangpin34** [comment]
Close this issue cause no further details provided.
