### ISSUE TITLE
[Vue warn]: Failed to resolve directive: v-scroll

### ISSUE THREAD

**Issue by drasnop** [wangpin34/vue-scroll#21]
From the Readme, it was not clear to me that I had to add:
```
import VueScroll from 'vue-scroll';
Vue.use(VueScroll);
```
in main.js before being able to use the v-scroll directive. Maybe this could be added to the Readme?

**Comment by wangpin34** [comment]
Done in this commit https://github.com/wangpin34/vue-scroll/commit/a14af8559e9a049b1cfdf858bd18bdfb636f6707. And really appreciate your report.
