### ISSUE TITLE
There are no listener could be removed

### ISSUE THREAD

**Issue by qianL93** [wangpin34/vue-scroll#23]
路由切换的时候出现以上警告

**Comment by wangpin34** [comment]
@qianL93 能share一下你的代码？

**Comment by qianL93** [comment]
@wangpin34 
`var eventFuncs;
                    if(!funcs[eventType] || (eventFuncs = funcs[eventType]).indexOf(func) < 0){
                      console.warn('There are no listener could be removed.');
                      return;
                    }`
这块老代码，npm上2.0.3的版本很久没更新了吧

**Comment by wangpin34** [comment]
@qianL93 v2.1.0 publish 了，请使用npm上最新版本测试一下，谢谢。

如果依然报错，请重新打开这个 issue，我们再讨论。
