### ISSUE TITLE
Error in directive scroll unbind hook: "TypeError: Cannot read property 'fn' of undefined"

### ISSUE THREAD

**Issue by eiamei** [wangpin34/vue-scroll#24]
**Versions:**
VueJs: 2.5.8
vue-scroll: 2.1.0

**Description**
After update to vue-scroll: 2.1.0 on change page got error:
Error in directive scroll unbind hook: "TypeError: Cannot read property 'fn' of undefined"
I try to install vue-scroll 2.0.3 again and it works fine, I can't reproduce same error again.

**Steps To Reproduce:**

1. Update to version vue-scroll to latest: 2.1.0
2. Load any page which is contain vue-scroll
3. Go to another page on site (with VueRouter if it's matter), example http://site.com/firstPage -> http://site.com/secondPage
4. OOPS, see an error in console

In this function: unbind (vue-scroll.js?2899:71)
```
unbind: function(el, binding) {
      let fn, fnOld, opt = null;

      fn = _.isFunction(binding.value) ? binding.value : binding.value.fn;
      fnOld = _.isFunction(binding.oldValue) ? binding.oldValue : binding.oldValue.fn;

      dom.unbind(el, SCROLL, fn);
      dom.unbind(el, SCROLL, fnOld);
}
```
```
binding.oldValue = undefined 
```
and that's a problem. If it's matter - binding.value is a function.

**Logs** 
TypeError: Cannot read property 'fn' of undefined
    at unbind (vue-scroll.js?2899:71)
    at callHook$1 (vue.runtime.esm.js?a427:6132)
    at _update (vue.runtime.esm.js?a427:6096)
    at updateDirectives (vue.runtime.esm.js?a427:6038)
    at Array.unbindDirectives (vue.runtime.esm.js?a427:6032)
    at invokeDestroyHook (vue.runtime.esm.js?a427:5601)
    at invokeDestroyHook (vue.runtime.esm.js?a427:5605)
    at invokeDestroyHook (vue.runtime.esm.js?a427:5605)
    at VueComponent.patch [as __patch__] (vue.runtime.esm.js?a427:5923)
    at VueComponent.Vue.$destroy (vue.runtime.esm.js?a427:2672)

**Comment by raulhuelamo** [comment]
+1, I'm also experiencing this issue

**Comment by wangpin34** [comment]
@eiamei Thanks for your report. It's very helpful.  I have made a mistake here in the hook to handle the values and your post helps me figure out what exactly happened and how to reproduce it easily at my machine.  Actually I already published **v.2.1.1** just now for fixing the defect.  Please feel free to test on it and let me know if any kind of problems.

By the way, glad to know you @eiamei @raulhuelamo. :)

If someone else still can reproduce kind of problem, please reopen this issue. Thanks.

**Comment by raulhuelamo** [comment]
Thanks for the quick fix @wangpin34 ! glad to know you also, I will be around

**Comment by eiamei** [comment]
It works well now, thanks @wangpin34 for so quick fix. Glad to know you too.
