### ISSUE TITLE
dist folder for releases

### ISSUE THREAD

**Issue by thomasv** [wangpin34/vue-scroll#27]
It would be great if there could be an official dist folder including the current release in ES5. This could make it easier to use vue-scroll with i.e. [uglify-js](https://github.com/mishoo/UglifyJS2). It is done this way i.e. by [vue-router](https://github.com/vuejs/vue-router/) or [vuex](https://github.com/vuejs/vuex), too.

**Comment by wangpin34** [comment]
Added umd, commonjs and es6 in dist folder. Have fun :).

**Comment by thomasv** [comment]
Thank you, that's great!

**Comment by wangpin34** [comment]
@thomasv Thank you.
