### ISSUE TITLE
Error: Map is not defined while using the lib on IE 10

### ISSUE THREAD

**Issue by jianjun6668** [wangpin34/vue-scroll#32]

**Comment by wangpin34** [comment]
@jianjun6668 Are you able to fix the issue on the browser you have tried? I don't have lower version IE installed at my laptop.

**Comment by wangpin34** [comment]
fixed by https://github.com/wangpin34/vue-scroll/commit/72492382d91090ca7b9f8946ae635eeb6951cc3b
