### ISSUE TITLE
(sorry if false) but why not implement passive event listener to increase performance?

### ISSUE THREAD

**Issue by pmochine** [wangpin34/vue-scroll#33]
Just had a look at your code and couldn't find that you use {passive: true}

Here is one simple react example, but the idea is the same:

https://github.com/rehooks/window-scroll-position/blob/master/index.js

https://stackoverflow.com/questions/37721782/what-are-passive-event-listeners

(Maybe I didn't see it here, but just saying :)

**Comment by wangpin34** [comment]
Thank you very much @pmochine .  I have not been aware of this feature. After read more articles about it after reading your post, I'm certainly sure it's a great idea of passive listener to improve the performance of scroll.  However, I'd like to have more test/practices by myself before make it in the project.  If you are interested in it, please feel free to create PR. 

Btw, welcome PR and Ideas all the time.

**Comment by muster-mark** [comment]
Was interested in this, but it's a no-go without passive listeners. Will this happen?

**Comment by wangpin34** [comment]
I left Vue quite long so no idea if this feature still valid. Maybe it's already there. I will close this issue for now. It's always ok to re-create another one for this. 

@pmochine  @muster-mark
