### ISSUE TITLE
How to import and use this directive

### ISSUE THREAD

**Issue by erensogut543** [wangpin34/vue-scroll#34]
![image](https://user-images.githubusercontent.com/30908572/52699161-2b4b7780-2f86-11e9-9915-ef7dc8798856.png)

I'm using webpack and vue cli 3 as a workspace. I downloaded the latest release but I can not inject it correctly to my project. Can you explain it step by step?

**Comment by wangpin34** [comment]
@erensogut543  Sorry for the late reply.  Have you try the demo under https://github.com/wangpin34/vue-scroll/tree/2.0-compatible/samples/vue-cli-webpack? Standalone  is an old build and what you do is download the source and "import" it by adding it in script tag.

**Comment by wangpin34** [comment]
Close this issue and please feel free to reopen if any related problems.
