### ISSUE TITLE
Console Error when reloading Vue component

### ISSUE THREAD

**Issue by desainr** [wangpin34/vue-scroll#35]
Hello, I have an app that reloads a Vue component when scrolling to the top or bottom of the page. I am getting the following console error: 

```
vue-scroll.esm.js:30 Uncaught TypeError: Cannot read property 'scrollTop' of null
    at HTMLDivElement.fn (vue-scroll.esm.js:30)
    at invokeFunc (debounce.js:95)
    at trailingEdge (debounce.js:144)
    at timerExpired (debounce.js:132)
```
It is not 100% reproducible, but seems to happen when scrolling quickly or quickly back and forth. Looking into the code it seems like the event target is undefined in this case. Would it be appropriate to have a null check on `target` in the `addEventListener()` sub method `fn()` ?

**Comment by sseelbach** [comment]
+1

**Comment by wangpin34** [comment]
Fixed in https://github.com/wangpin34/vue-scroll/releases/tag/v2.1.12
