### ISSUE TITLE
Detect end?

### ISSUE THREAD

**Issue by movepixels** [wangpin34/vue-scroll#39]
I did not see anywhere about events?

I have a textbox scrolling fine but I need to user to scroll to the very bottom to trigger some other function.

How can I @someEvent = bottom of scroll area is reached?

Thanks

**Comment by wangpin34** [comment]
There is no such thing down here. But you can still catch it by leveraging some of the properties like scroll top, scroll height depends on the real element.  Hope this could help to solve your issue.
