### ISSUE TITLE
Still get debug log in production environment.

### ISSUE THREAD

**Issue by yunhao** [wangpin34/vue-scroll#4]
After build my project and access the built files (dist) over HTTP server,  I still find some debug information printed by vue-scroll. Is there some options that I need to do?

![image](https://cloud.githubusercontent.com/assets/10205466/18865579/9ec04070-84ce-11e6-8203-f7b336c43268.png)

**Comment by wangpin34** [comment]
@duanyunhao  Currently no more options for that. Very glad to get the point from you. Would you please help to improve this project?  You idea is very previous. :+1:

**Comment by wangpin34** [comment]
Strip all debug statements in distribution https://github.com/wangpin34/vue-scroll/commit/63d65aca9feea0a8efb3b5f0722b489e731b1bed
