### ISSUE TITLE
Not working at all for me, what am I missing?

### ISSUE THREAD

**Issue by flyingL123** [wangpin34/vue-scroll#41]
I'm not sure what I'm doing wrong. I'm not getting any calls to my `onScroll` method when I scroll the page. Can someone help?

This is my HTML:

```
<div id="syb-app">
    <div v-scroll="onScroll"></div>
    <!-- The rest of my markup -->
</div>
```

And the js:

```
import Vue from 'vue';
import vuescroll from 'vue-scroll';

Vue.use(vuescroll, {debounce: 100});

const app = new Vue({
    el: '#syb-app',

    methods: {
        onScroll: function (e, position) {
            console.log(e, position);
        }
    }
});
```

No matter what I do, `onScroll` is never called. Am I missing something very obvious here? I am just trying to detect when the page is scrolled.

**Comment by jung-hunsoo** [comment]
I'm getting the same problem. It maybe related to #1

**Comment by wangpin34** [comment]
@flyingL123 Could you please create a sample on codesandbox for your issue?
By the way, here is a demo I created for getting started of vue-scroll: [vuescroll-demo-orders-view](https://codesandbox.io/s/vuescroll-demo-orders-view-f4d3d?fontsize=14)

**Comment by wangpin34** [comment]
Close it since no more reply.

@flyingL123  @jung-hunsoo  Please reopen this issue when you need.
