### ISSUE TITLE
貌似不支持vue2.0

### ISSUE THREAD

**Issue by liucaihe** [wangpin34/vue-scroll#5]
貌似不支持vue2.0。

**Comment by wangpin34** [comment]
@LiuCaiHe  是的，目前的1.0.4不支持vue2.0。我会在下一个版本1.1.0中加入对vue2.0的支持。如果你有兴趣，也可以自行开发然后提交你的代码。

最后，谢谢你的发现。

**Comment by wangpin34** [comment]
vue-scroll 2.0.0 is published to support vue 2.0. Close this bug.

**Comment by wangpin34** [comment]
vue-scroll 2.0.0 is published to support vue 2.0. Close this bug.
