### ISSUE TITLE
Vue-cli/webpack example

### ISSUE THREAD

**Issue by template01** [wangpin34/vue-scroll#9]
Hi! 

I'm kinda new to Vue. I'm using the Vue-cli for running my projects. Could you provide an example of how to import and implement vue-scroll in such a setup? 

Thaaanks 

Lasse

**Comment by wangpin34** [comment]
@template01 Created a sample for that.  https://github.com/wangpin34/vue-scroll/tree/2.0-compatible/samples/vue-cli-webpack.  The main step that add vue-scroll into your project is:

* Import vue-scroll
```
import scroll from 'vue-scroll'
```
* Load it as a [plugin](https://vuejs.org/v2/guide/plugins.html#Using-a-Plugin)
```
Vue.use(scroll )
```
* Then follow this [doc](https://github.com/wangpin34/vue-scroll#usage) before you start it.

thanks.

**Comment by wangpin34** [comment]
Please reopen this if any help needed.
